# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170317_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(default='ebook_img.jpeg', upload_to='img/'),
        ),
    ]
